from langchain_ollama import ChatOllama
import streamlit as st 
from langchain_core.messages import HumanMessage ,AIMessage , SystemMessage 

model = ChatOllama(model='llama3')
chat_history =[
    SystemMessage(content='your are good ai')
] # this problems is solved but new pronlems is that  data 
# data stored in chathistory how to llm know which is askeb by human and answer generated by llm 


# start leveling the our humna and System and ai genereted 
while True:
    user_input = input('You : ')
    chat_history.append(HumanMessage(content=user_input))
    if user_input=='exit' or user_input =='Exit':
        break
    result = model.invoke(chat_history)  # we were maintaining user and ai answer both 
    # this is ways to append 
    chat_history.append(AIMessage(content=result.content))
    print('AI :' , result.content)

print(chat_history)

