from langchain_ollama import ChatOllama
import streamlit as st 
from langchain_core.messages
model = ChatOllama(model='llama3')
chat_history =[] # this problems is solved but new pronlems is that  data 
# data stored in chathistory how to llm know which is askeb by human and answer generated by llm 

while True:
    user_input = input('You : ')
    chat_history.append(user_input)
    if user_input=='exit' or user_input =='Exit':
        break
    result = model.invoke(chat_history)  # we were maintaining user and ai answer both 
    chat_history.append(result)
    print('AI :' , result.content)

print(chat_history)

